# push 동작을 할떄 동작하도록
on: push
name: Test and Make Debug APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
      # google-json test
      - name: Make google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
      # env 파일 생성로직..
      - name: Setting .env
        run : |
          echo "TEMP_GOOGLE_KEY=${{ secrets.TEMP_GOOGLE_KEY}}" >> .env
          cat .env
      - run: flutter pub get
      - run: flutter test
      # apk 작성
      - run: flutter build apk --debug
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}

      - run: flutter build apk